//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ExpressFormsExample
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExpressFormsExampleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExpressFormsExampleEntities object using the connection string found in the 'ExpressFormsExampleEntities' section of the application configuration file.
        /// </summary>
        public ExpressFormsExampleEntities() : base("name=ExpressFormsExampleEntities", "ExpressFormsExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpressFormsExampleEntities object.
        /// </summary>
        public ExpressFormsExampleEntities(string connectionString) : base(connectionString, "ExpressFormsExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpressFormsExampleEntities object.
        /// </summary>
        public ExpressFormsExampleEntities(EntityConnection connection) : base(connection, "ExpressFormsExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Engineer> Engineers
        {
            get
            {
                if ((_Engineers == null))
                {
                    _Engineers = base.CreateObjectSet<Engineer>("Engineers");
                }
                return _Engineers;
            }
        }
        private ObjectSet<Engineer> _Engineers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NumberSequence> NumberSequences
        {
            get
            {
                if ((_NumberSequences == null))
                {
                    _NumberSequences = base.CreateObjectSet<NumberSequence>("NumberSequences");
                }
                return _NumberSequences;
            }
        }
        private ObjectSet<NumberSequence> _NumberSequences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NameAndCity> NameAndCities
        {
            get
            {
                if ((_NameAndCities == null))
                {
                    _NameAndCities = base.CreateObjectSet<NameAndCity>("NameAndCities");
                }
                return _NameAndCities;
            }
        }
        private ObjectSet<NameAndCity> _NameAndCities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Month> Months
        {
            get
            {
                if ((_Months == null))
                {
                    _Months = base.CreateObjectSet<Month>("Months");
                }
                return _Months;
            }
        }
        private ObjectSet<Month> _Months;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Engineers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEngineers(Engineer engineer)
        {
            base.AddObject("Engineers", engineer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NumberSequences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNumberSequences(NumberSequence numberSequence)
        {
            base.AddObject("NumberSequences", numberSequence);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NameAndCities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNameAndCities(NameAndCity nameAndCity)
        {
            base.AddObject("NameAndCities", nameAndCity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Months EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMonths(Month month)
        {
            base.AddObject("Months", month);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpressFormsExampleModel", Name="Engineer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Engineer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Engineer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="available">Initial value of the Available property.</param>
        public static Engineer CreateEngineer(global::System.Int32 id, global::System.Boolean available)
        {
            Engineer engineer = new Engineer();
            engineer.Id = id;
            engineer.Available = available;
            return engineer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Available
        {
            get
            {
                return _Available;
            }
            set
            {
                OnAvailableChanging(value);
                ReportPropertyChanging("Available");
                _Available = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Available");
                OnAvailableChanged();
            }
        }
        private global::System.Boolean _Available;
        partial void OnAvailableChanging(global::System.Boolean value);
        partial void OnAvailableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FavoriteLanguage
        {
            get
            {
                return _FavoriteLanguage;
            }
            set
            {
                OnFavoriteLanguageChanging(value);
                ReportPropertyChanging("FavoriteLanguage");
                _FavoriteLanguage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FavoriteLanguage");
                OnFavoriteLanguageChanged();
            }
        }
        private global::System.String _FavoriteLanguage;
        partial void OnFavoriteLanguageChanging(global::System.String value);
        partial void OnFavoriteLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodeSnippet
        {
            get
            {
                return _CodeSnippet;
            }
            set
            {
                OnCodeSnippetChanging(value);
                ReportPropertyChanging("CodeSnippet");
                _CodeSnippet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodeSnippet");
                OnCodeSnippetChanged();
            }
        }
        private global::System.String _CodeSnippet;
        partial void OnCodeSnippetChanging(global::System.String value);
        partial void OnCodeSnippetChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpressFormsExampleModel", Name="Month")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Month : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Month object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numDaysByte">Initial value of the NumDaysByte property.</param>
        /// <param name="numDaysShort">Initial value of the NumDaysShort property.</param>
        /// <param name="numDaysInt">Initial value of the NumDaysInt property.</param>
        /// <param name="numDaysLong">Initial value of the NumDaysLong property.</param>
        /// <param name="numDaysSingle">Initial value of the NumDaysSingle property.</param>
        public static Month CreateMonth(global::System.Int32 id, global::System.Byte numDaysByte, global::System.Int16 numDaysShort, global::System.Int32 numDaysInt, global::System.Int64 numDaysLong, global::System.Single numDaysSingle)
        {
            Month month = new Month();
            month.Id = id;
            month.NumDaysByte = numDaysByte;
            month.NumDaysShort = numDaysShort;
            month.NumDaysInt = numDaysInt;
            month.NumDaysLong = numDaysLong;
            month.NumDaysSingle = numDaysSingle;
            return month;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MonthName
        {
            get
            {
                return _MonthName;
            }
            set
            {
                OnMonthNameChanging(value);
                ReportPropertyChanging("MonthName");
                _MonthName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MonthName");
                OnMonthNameChanged();
            }
        }
        private global::System.String _MonthName;
        partial void OnMonthNameChanging(global::System.String value);
        partial void OnMonthNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NumDaysByte
        {
            get
            {
                return _NumDaysByte;
            }
            set
            {
                OnNumDaysByteChanging(value);
                ReportPropertyChanging("NumDaysByte");
                _NumDaysByte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumDaysByte");
                OnNumDaysByteChanged();
            }
        }
        private global::System.Byte _NumDaysByte;
        partial void OnNumDaysByteChanging(global::System.Byte value);
        partial void OnNumDaysByteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 NumDaysShort
        {
            get
            {
                return _NumDaysShort;
            }
            set
            {
                OnNumDaysShortChanging(value);
                ReportPropertyChanging("NumDaysShort");
                _NumDaysShort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumDaysShort");
                OnNumDaysShortChanged();
            }
        }
        private global::System.Int16 _NumDaysShort;
        partial void OnNumDaysShortChanging(global::System.Int16 value);
        partial void OnNumDaysShortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumDaysInt
        {
            get
            {
                return _NumDaysInt;
            }
            set
            {
                OnNumDaysIntChanging(value);
                ReportPropertyChanging("NumDaysInt");
                _NumDaysInt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumDaysInt");
                OnNumDaysIntChanged();
            }
        }
        private global::System.Int32 _NumDaysInt;
        partial void OnNumDaysIntChanging(global::System.Int32 value);
        partial void OnNumDaysIntChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NumDaysLong
        {
            get
            {
                return _NumDaysLong;
            }
            set
            {
                OnNumDaysLongChanging(value);
                ReportPropertyChanging("NumDaysLong");
                _NumDaysLong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumDaysLong");
                OnNumDaysLongChanged();
            }
        }
        private global::System.Int64 _NumDaysLong;
        partial void OnNumDaysLongChanging(global::System.Int64 value);
        partial void OnNumDaysLongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single NumDaysSingle
        {
            get
            {
                return _NumDaysSingle;
            }
            set
            {
                OnNumDaysSingleChanging(value);
                ReportPropertyChanging("NumDaysSingle");
                _NumDaysSingle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumDaysSingle");
                OnNumDaysSingleChanged();
            }
        }
        private global::System.Single _NumDaysSingle;
        partial void OnNumDaysSingleChanging(global::System.Single value);
        partial void OnNumDaysSingleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NumDaysDouble
        {
            get
            {
                return _NumDaysDouble;
            }
            set
            {
                OnNumDaysDoubleChanging(value);
                ReportPropertyChanging("NumDaysDouble");
                _NumDaysDouble = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumDaysDouble");
                OnNumDaysDoubleChanged();
            }
        }
        private Nullable<global::System.Double> _NumDaysDouble;
        partial void OnNumDaysDoubleChanging(Nullable<global::System.Double> value);
        partial void OnNumDaysDoubleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CanChangeNumDays
        {
            get
            {
                return _CanChangeNumDays;
            }
            set
            {
                OnCanChangeNumDaysChanging(value);
                ReportPropertyChanging("CanChangeNumDays");
                _CanChangeNumDays = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanChangeNumDays");
                OnCanChangeNumDaysChanged();
            }
        }
        private Nullable<global::System.Boolean> _CanChangeNumDays;
        partial void OnCanChangeNumDaysChanging(Nullable<global::System.Boolean> value);
        partial void OnCanChangeNumDaysChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpressFormsExampleModel", Name="NameAndCity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NameAndCity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NameAndCity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static NameAndCity CreateNameAndCity(global::System.Int32 id)
        {
            NameAndCity nameAndCity = new NameAndCity();
            nameAndCity.Id = id;
            return nameAndCity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Middle_Name
        {
            get
            {
                return _Middle_Name;
            }
            set
            {
                OnMiddle_NameChanging(value);
                ReportPropertyChanging("Middle_Name");
                _Middle_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Middle_Name");
                OnMiddle_NameChanged();
            }
        }
        private global::System.String _Middle_Name;
        partial void OnMiddle_NameChanging(global::System.String value);
        partial void OnMiddle_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpressFormsExampleModel", Name="NumberSequence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NumberSequence : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NumberSequence object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="prime">Initial value of the Prime property.</param>
        /// <param name="composite">Initial value of the Composite property.</param>
        public static NumberSequence CreateNumberSequence(global::System.Int32 id, global::System.Int32 prime, global::System.Int32 composite)
        {
            NumberSequence numberSequence = new NumberSequence();
            numberSequence.Id = id;
            numberSequence.Prime = prime;
            numberSequence.Composite = composite;
            return numberSequence;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Prime
        {
            get
            {
                return _Prime;
            }
            set
            {
                OnPrimeChanging(value);
                ReportPropertyChanging("Prime");
                _Prime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prime");
                OnPrimeChanged();
            }
        }
        private global::System.Int32 _Prime;
        partial void OnPrimeChanging(global::System.Int32 value);
        partial void OnPrimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Composite
        {
            get
            {
                return _Composite;
            }
            set
            {
                OnCompositeChanging(value);
                ReportPropertyChanging("Composite");
                _Composite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Composite");
                OnCompositeChanged();
            }
        }
        private global::System.Int32 _Composite;
        partial void OnCompositeChanging(global::System.Int32 value);
        partial void OnCompositeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }

    #endregion

    
}
