//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ExpressFormsExample
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExpressFormsExampleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExpressFormsExampleEntities object using the connection string found in the 'ExpressFormsExampleEntities' section of the application configuration file.
        /// </summary>
        public ExpressFormsExampleEntities() : base("name=ExpressFormsExampleEntities", "ExpressFormsExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpressFormsExampleEntities object.
        /// </summary>
        public ExpressFormsExampleEntities(string connectionString) : base(connectionString, "ExpressFormsExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpressFormsExampleEntities object.
        /// </summary>
        public ExpressFormsExampleEntities(EntityConnection connection) : base(connection, "ExpressFormsExampleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Engineer> Engineers
        {
            get
            {
                if ((_Engineers == null))
                {
                    _Engineers = base.CreateObjectSet<Engineer>("Engineers");
                }
                return _Engineers;
            }
        }
        private ObjectSet<Engineer> _Engineers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Engineers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEngineers(Engineer engineer)
        {
            base.AddObject("Engineers", engineer);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpressFormsExampleModel", Name="Engineer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Engineer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Engineer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="available">Initial value of the Available property.</param>
        public static Engineer CreateEngineer(global::System.Int32 id, global::System.Boolean available)
        {
            Engineer engineer = new Engineer();
            engineer.Id = id;
            engineer.Available = available;
            return engineer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Available
        {
            get
            {
                return _Available;
            }
            set
            {
                OnAvailableChanging(value);
                ReportPropertyChanging("Available");
                _Available = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Available");
                OnAvailableChanged();
            }
        }
        private global::System.Boolean _Available;
        partial void OnAvailableChanging(global::System.Boolean value);
        partial void OnAvailableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FavoriteLanguage
        {
            get
            {
                return _FavoriteLanguage;
            }
            set
            {
                OnFavoriteLanguageChanging(value);
                ReportPropertyChanging("FavoriteLanguage");
                _FavoriteLanguage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FavoriteLanguage");
                OnFavoriteLanguageChanged();
            }
        }
        private global::System.String _FavoriteLanguage;
        partial void OnFavoriteLanguageChanging(global::System.String value);
        partial void OnFavoriteLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodeSnippet
        {
            get
            {
                return _CodeSnippet;
            }
            set
            {
                OnCodeSnippetChanging(value);
                ReportPropertyChanging("CodeSnippet");
                _CodeSnippet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodeSnippet");
                OnCodeSnippetChanged();
            }
        }
        private global::System.String _CodeSnippet;
        partial void OnCodeSnippetChanging(global::System.String value);
        partial void OnCodeSnippetChanged();

        #endregion

    
    }

    #endregion

    
}
